name: release
on:
  release:
    types: [ published ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Run image
        uses: abatilo/actions-poetry@v3
      - name: Install deps
        run: poetry install
      - name: Build and release to PyPI
        run: |
          # poetry source add testpypi "https://test.pypi.org/legacy/"
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish --build
